# Generated by Django 2.2.14 on 2021-07-14 06:28

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128)),
                ('question', models.CharField(max_length=128)),
                ('response', models.CharField(max_length=512)),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(blank=True, default=None, max_length=128, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
